Fix test report path

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -25,3 +25,10 @@ jobs:
       run: dotnet build --no-restore
     - name: Unit tests
       run: dotnet test --verbosity normal --no-build --filter "FullyQualifiedName~Tests.Unit" --logger "trx;LogFileName=test-results.trx"
+    - name: Unit tests report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Unit tests
+        path: '**/test-results.trx'
+        reporter: dotnet-trx
