Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -23,5 +23,12 @@ jobs:
       run: dotnet restore
     - name: Build
       run: dotnet build --no-restore
-    - name: Tests - Unit
-      run: dotnet test --verbosity normal --no-build --filter "FullyQualifiedName~Tests.Unit"
+    - name: Unit Tests
+      run: dotnet test --verbosity normal --no-build --filter "FullyQualifiedName~Tests.Unit" --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults"
+    - name: Test Report
+      uses: dorny/test-reporter@v1
+      if: success() || failure()    # run this step even if previous step failed
+      with:
+        name: Unit Tests            # Name of the check run which will be created
+        path: TestResults/test-results.trx    # Path to test results
+        reporter: dotnet-trx        # Format of test results
